// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.mjs";
import * as HexagonUtil from "./HexagonUtil.bs.js";

var hexagon = HexagonUtil.createHexagon(30.0);

function Hexagon(Props) {
  var column = Props.column;
  var row = Props.row;
  var match = HexagonUtil.calcHexagonPosition(column, row, 30.0);
  var offsetY = match[1];
  var offsetX = match[0];
  console.log(offsetX, offsetY);
  return React.createElement("polygon", {
              fill: column % 2 === 0 ? "#ff77ff" : "#77ffff",
              points: Belt_Array.reduce(Belt_Array.map(hexagon, (function (param) {
                          return String(param[0] + offsetX) + "," + String(param[1] + offsetY);
                        })), " ", (function (acc, x) {
                      return acc + " " + x;
                    }))
            });
}

var defaultWidth = 30.0;

var make = Hexagon;

export {
  hexagon ,
  defaultWidth ,
  make ,
  
}
/* hexagon Not a pure module */
