// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "bs-platform/lib/es6/js_math.mjs";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.mjs";

function makeHexagonBuilder(size) {
  var width = 2.0 * size;
  var height = Math.sqrt(3.0) * size;
  var pointyOffset = size * 1.5;
  var isEven = function (value) {
    return value % 2 === 0;
  };
  var hexagon = [
    [
      width,
      height / 2.0
    ],
    [
      width * 3.0 / 4.0,
      height
    ],
    [
      width / 4.0,
      height
    ],
    [
      0.0,
      height / 2.0
    ],
    [
      width / 4.0,
      0.0
    ],
    [
      width * 3.0 / 4.0,
      0.0
    ]
  ];
  var getPosition = function (column, row) {
    return [
            column * size * 3.0 + (
              isEven(row) ? pointyOffset : 0.0
            ),
            row * (Math.sqrt(3.0) * size / 2.0)
          ];
  };
  return {
          getHexagonAt: (function (column, row) {
              var match = getPosition(column, row);
              var posY = match[1];
              var posX = match[0];
              return Belt_Array.map(hexagon, (function (param) {
                            return [
                                    param[0] + posX,
                                    param[1] + posY
                                  ];
                          }));
            }),
          getWorldRect: (function (columns, rows) {
              return {
                      x: 0.0,
                      y: 0.0,
                      width: Js_math.ceil(3.0 * size * columns + 0.5 * size),
                      height: Js_math.ceil((height * rows + height) / 2.0)
                    };
            })
        };
}

export {
  makeHexagonBuilder ,
  
}
/* No side effect */
