// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.mjs";

function createHexagon(width) {
  return [
          [
            width,
            width / 2 | 0
          ],
          [
            Math.imul(width, 3) / 4 | 0,
            Math.imul(width, 56) / 60 | 0
          ],
          [
            width / 4 | 0,
            Math.imul(width, 56) / 60 | 0
          ],
          [
            0,
            width / 2 | 0
          ],
          [
            width / 4 | 0,
            (width << 2) / 60 | 0
          ],
          [
            Math.imul(width, 3) / 4 | 0,
            (width << 2) / 60 | 0
          ]
        ];
}

var hexagon = createHexagon(60);

function Hexagon(Props) {
  var column = Props.column;
  return React.createElement("polygon", {
              fill: "#ff77ff",
              points: Belt_Array.reduce(Belt_Array.map(hexagon, (function (param) {
                          return String(param[0] + Math.imul(column, 60) | 0) + "," + String(param[1] + Math.imul(column % 10, 60) | 0);
                        })), " ", (function (acc, x) {
                      return acc + " " + x;
                    }))
            });
}

var defaultWidth = 60;

var rowLength = 10;

var make = Hexagon;

export {
  createHexagon ,
  hexagon ,
  defaultWidth ,
  rowLength ,
  make ,
  
}
/* hexagon Not a pure module */
