// Generated by ReScript, PLEASE EDIT WITH CARE


function createHexagon(size) {
  var width = 2.0 * size;
  var height = Math.sqrt(3.0) * size;
  return [
          [
            width,
            height / 2.0
          ],
          [
            width * 3.0 / 4.0,
            height
          ],
          [
            width / 4.0,
            height
          ],
          [
            0.0,
            height / 2.0
          ],
          [
            width / 4.0,
            0.0
          ],
          [
            width * 3.0 / 4.0,
            0.0
          ]
        ];
}

function calcPointyGapOdd(size) {
  return size * 1.5;
}

function isEven(value) {
  return value % 2 === 0;
}

function calcHexagonPosition(column, row, size) {
  return [
          column * size * 3.0 + (
            isEven(row) ? 0.0 : size * 1.5
          ),
          row * (Math.sqrt(3.0) * size / 2.0)
        ];
}

export {
  createHexagon ,
  calcPointyGapOdd ,
  isEven ,
  calcHexagonPosition ,
  
}
/* No side effect */
