// Generated by ReScript, PLEASE EDIT WITH CARE

import * as World from "./World.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

ReactDom.render(React.createElement(World.make, {}), document.getElementById("root"));

export {
  
}
/*  Not a pure module */
