// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Tree(Props) {
  var x = Props.x;
  var y = Props.y;
  return React.createElement("svg", {
              height: "59.4px",
              width: "42px",
              version: "1.1",
              viewBox: "0 0 210 297",
              x: "" + x,
              xmlns: "http://www.w3.org/2000/svg",
              y: "" + y
            }, React.createElement("defs", undefined, React.createElement("linearGradient", {
                      id: "a",
                      gradientTransform: "matrix(.0012966 0 0 .0012966 28.004 41.579)"
                    }, React.createElement("stop", {
                          offset: "0",
                          stopColor: "#2a5"
                        }))), React.createElement("g", {
                  transform: "translate(29.577 -13.796)"
                }, React.createElement("path", {
                      d: "m36.38 71.694h2.6458l1.3229 34.14h-5.2917z",
                      fill: "#d38d5f",
                      strokeWidth: ".33342"
                    }), React.createElement("path", {
                      d: "m37.703 39.688-8.0698 12.7h2.9104l-6.8792 10.848h3.4396l-7.4083 13.494h3.9688l-8.4667 17.198h41.01l-8.4667-17.198h3.9688l-7.4083-13.494h3.4396l-6.8792-10.848h2.6458z",
                      fill: "url(#a)",
                      strokeWidth: ".21941"
                    }), React.createElement("path", {
                      d: "m32.544 52.388 11.969 2.6019-1.65-2.6019z",
                      fillOpacity: ".1",
                      strokeWidth: ".21941"
                    }), React.createElement("path", {
                      d: "m29.104 63.235 19.479 4.1558-2.2815-4.1558z",
                      fillOpacity: ".1",
                      strokeWidth: ".21941"
                    }), React.createElement("path", {
                      d: "m25.665 76.729 26.622 5.1692-2.5451-5.1692z",
                      fillOpacity: ".1",
                      strokeWidth: ".21941"
                    }), React.createElement("path", {
                      d: "m37.703 39.687v54.24h20.505l-8.4667-17.198h3.9688l-7.4083-13.494h3.4396l-6.8792-10.848h2.6458z",
                      fillOpacity: ".098039",
                      strokeWidth: ".21941"
                    }), React.createElement("path", {
                      d: "m37.703 93.927v11.906h2.6458l-0.46104-11.906z",
                      fillOpacity: ".098039",
                      strokeWidth: ".33364"
                    }), React.createElement("path", {
                      d: "m37.703 93.92 2.3385 3.9755-0.15415-3.9755z",
                      fillOpacity: ".098039",
                      strokeWidth: ".33342"
                    })));
}

var make = Tree;

export {
  make ,
  
}
/* react Not a pure module */
