// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Hexagon from "./Hexagon.bs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.mjs";

function World(Props) {
  return React.createElement("svg", {
              height: "600",
              width: "600"
            }, Belt_Array.makeBy(36, (function (i) {
                    return React.createElement(Hexagon.make, {
                                column: i % 4,
                                row: i / 4 | 0,
                                key: String(i)
                              });
                  })));
}

var rowLength = 4;

var make = World;

export {
  rowLength ,
  make ,
  
}
/* react Not a pure module */
